Update baj-concordia.js
thymepuns/concordia-enhancements pull request #5
Opened 2019-11-13 23:37 UTC by thiefofsanity

Here ya go!

2019-11-13 23:40 UTC, thymepuns requested changes
Thank you for the PR. Please move your code comments into the PR comments instead.

2019-11-13 23:40 UTC, thymepuns commented on baj-concordia.js
> +  // David can't spell. 🙄🙄
```suggestion
```

2019-11-13 23:40 UTC, thymepuns commented on baj-concordia.js
> +   // So this fixes the spelling mistake. 🤞
```suggestion
```

2019-11-13 23:40 UTC, thymepuns commented on baj-concordia.js
> +   // While also offering delightful commentary. 😈😈😈😈😈
```suggestion
```

2019-11-13 23:42 UTC, thiefofsanity commented
Well, that's just rude! What about the other emoji? Why are they allowed?

2019-11-14 00:01 UTC, thymepuns approved these changes
👍 LGTM

2019-11-14 00:01 UTC, merged